SELECT TOP (1000) [ID]
      ,[Date]
      ,[Product]
      ,[Category]
      ,[Revenue]
      ,[Cost]
      ,[Profit]
      ,[Region]
      ,[Customer]
  FROM [GithubProject].[dbo].[FinancialData]
